import type { Metadata } from "next";
import { sourceCodePro } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Tech Talks Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sourceCodePro.className}>{children}</body>
    </html>
  );
}
